// <auto-generated />
namespace PRSWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class madePurchaseRequestUseravirtualproperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(madePurchaseRequestUseravirtualproperty));
        
        string IMigrationMetadata.Id
        {
            get { return "201710032120015_made PurchaseRequest.User a virtual property"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
