// <auto-generated />
namespace PRSWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedpurchaserequestlineitem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedpurchaserequestlineitem));
        
        string IMigrationMetadata.Id
        {
            get { return "201710021834486_added purchase request line item"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
